language: node_js
node_js:
  - 10.15.3

script:
  - npm run gulp

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local_dir: build